"use client";

import { useState } from "react";
import { Scale, Download, AlertTriangle, X } from "lucide-react";

interface LetterDownloadDisclaimerProps {
  /** Whether the modal is visible */
  open: boolean;
  /** Called when user closes without proceeding */
  onClose: () => void;
  /** Called when user acknowledges and wants to download */
  onProceed: () => void;
  /** Type of document being downloaded */
  documentType: "letter" | "attorney-package" | "forensic-report";
}

const documentLabels: Record<string, { title: string; warning: string }> = {
  letter: {
    title: "Download Dispute Letter",
    warning:
      "This dispute letter is a self-help template generated by CreditClean AI for educational purposes. It is not legal advice and does not constitute legal representation.",
  },
  "attorney-package": {
    title: "Download Attorney Package",
    warning:
      'This attorney package is a litigation preparation document. It does NOT mean you have hired an attorney. "Attorney package" refers to a document package formatted for attorney review — you should consult a qualified consumer rights attorney before taking legal action.',
  },
  "forensic-report": {
    title: "Download Forensic Report",
    warning:
      "This forensic analysis report is generated by AI for educational and self-help purposes. The violations and damages estimates are informational only and have not been reviewed by a licensed attorney.",
  },
};

/**
 * Disclaimer modal shown before any PDF download.
 * Ensures users understand the document is self-help, not legal advice.
 */
export default function LetterDownloadDisclaimer({
  open,
  onClose,
  onProceed,
  documentType,
}: LetterDownloadDisclaimerProps) {
  const [acknowledged, setAcknowledged] = useState(false);
  const config = documentLabels[documentType] || documentLabels.letter;

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
      <div className="w-full max-w-md rounded-2xl border border-zinc-200 bg-white shadow-2xl dark:border-zinc-700 dark:bg-zinc-900">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-zinc-200 px-6 py-4 dark:border-zinc-700">
          <div className="flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-amber-50 dark:bg-amber-950/50">
              <Scale className="h-5 w-5 text-amber-600 dark:text-amber-400" />
            </div>
            <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100">
              {config.title}
            </h2>
          </div>
          <button
            onClick={onClose}
            className="rounded-md p-1 text-zinc-400 hover:bg-zinc-100 hover:text-zinc-600 dark:hover:bg-zinc-800 dark:hover:text-zinc-300"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Content */}
        <div className="space-y-4 px-6 py-5">
          <div className="rounded-lg border border-amber-200 bg-amber-50 p-4 dark:border-amber-800/50 dark:bg-amber-950/30">
            <div className="flex items-start gap-3">
              <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-600 dark:text-amber-400" />
              <p className="text-sm leading-relaxed text-amber-800 dark:text-amber-200">
                {config.warning}
              </p>
            </div>
          </div>

          <div className="space-y-2 text-sm text-zinc-600 dark:text-zinc-400">
            <p>Before using this document, please understand:</p>
            <ul className="list-disc space-y-1 pl-5">
              <li>You are responsible for the accuracy and truthfulness of all information in this document</li>
              <li>Review the letter carefully before sending — you may need to customize details</li>
              <li>Consider having a qualified consumer rights attorney review the document</li>
              <li>Sending a dispute letter with false claims can have legal consequences</li>
            </ul>
          </div>

          <label className="flex items-start gap-3 cursor-pointer rounded-lg border border-zinc-200 p-3 transition-colors hover:bg-zinc-50 dark:border-zinc-700 dark:hover:bg-zinc-800/50">
            <input
              type="checkbox"
              checked={acknowledged}
              onChange={(e) => setAcknowledged(e.target.checked)}
              className="mt-0.5 h-4 w-4 rounded border-zinc-300 text-teal-600 focus:ring-teal-500"
            />
            <span className="text-sm text-zinc-700 dark:text-zinc-300">
              I understand this is a self-help template, not legal advice, and I take
              responsibility for reviewing and using it appropriately.
            </span>
          </label>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end gap-3 border-t border-zinc-200 bg-zinc-50 px-6 py-4 dark:border-zinc-700 dark:bg-zinc-800/50">
          <button
            onClick={onClose}
            className="rounded-lg px-4 py-2.5 text-sm font-medium text-zinc-600 transition-colors hover:bg-zinc-200 dark:text-zinc-400 dark:hover:bg-zinc-700"
          >
            Cancel
          </button>
          <button
            onClick={() => {
              if (acknowledged) {
                setAcknowledged(false);
                onProceed();
              }
            }}
            disabled={!acknowledged}
            className="inline-flex items-center gap-2 rounded-lg bg-gradient-to-r from-teal-600 to-emerald-500 px-5 py-2.5 text-sm font-semibold text-white shadow-sm transition-all hover:shadow-md hover:brightness-110 disabled:opacity-40 disabled:cursor-not-allowed"
          >
            <Download className="h-4 w-4" />
            Download PDF
          </button>
        </div>
      </div>
    </div>
  );
}
